name: Sync

on:
  workflow_dispatch:
  schedule: [ { cron: "0 */12 * * *" } ]
  push: { branches: [ "master" ] }

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          make init
          make update
          make dist
      - run: |
          if [[ ! $(git status --porcelain) ]]; then echo 'no commit'; exit 0; fi;
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "sync [$(date +%FT%T)]"
          git push -u origin master
