name: Sync

permissions:
  repository-projects: write

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dist
        run: |
          make init
          make update
          make dist
      - name: Push
        run: |
          if [[ ! $(git status --porcelain) ]]; then echo 'no commit'; exit 0; fi;
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "sync [$(date +%FT%T)]"
          git push -u origin master
